USE Lab2DB;

CREATE TABLE Users (
    UserID   INT PRIMARY KEY IDENTITY,
    UserName NVARCHAR(100) NOT NULL,
    Email    NVARCHAR(150) NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    IsLocked BIT DEFAULT 0
);

CREATE TABLE Item (
    ItemID   INT PRIMARY KEY IDENTITY,
    ItemName NVARCHAR(200) NOT NULL,
    Size     NVARCHAR(50),
    Price    DECIMAL(18,2) DEFAULT 0
);

CREATE TABLE Agent (
    AgentID   INT PRIMARY KEY IDENTITY,
    AgentName NVARCHAR(200) NOT NULL,
    Address   NVARCHAR(300)
);

CREATE TABLE [Order] (
    OrderID   INT PRIMARY KEY IDENTITY,
    OrderDate DATETIME DEFAULT GETDATE(),
    AgentID   INT FOREIGN KEY REFERENCES Agent(AgentID)
);

CREATE TABLE OrderDetail (
    ID         INT PRIMARY KEY IDENTITY,
    OrderID    INT FOREIGN KEY REFERENCES [Order](OrderID),
    ItemID     INT FOREIGN KEY REFERENCES Item(ItemID),
    Quantity   INT DEFAULT 1,
    UnitAmount DECIMAL(18,2) DEFAULT 0
);